### ISSUE TITLE
[Week 2] Can't go back from current files of starting directory

### ISSUE THREAD

**Issue by aksh1618** [sonudoo/Git-Heat#2]
### Expected Behavior

Clicking *Back* shoud navigate back to starting directory.

### Actual Behaviour

Nothing happens on clicking *Back*.

### Steps to reproduce
1. Run for any directory with files.
2. Double click on section representing *Current Directory Files*.
3. Click *Back* button.

**Comment by sonudoo** [comment]
Resolved
